x-arcane:
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
  urls:
    - https://jellyfin.org/
    - https://github.com/jellyfin/jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    user: uid:gid
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${APPDATA_PATH}/jellyfin/config:/config
      - ${APPDATA_PATH}/jellyfin/cache:/cache
      - type: bind
        source: ${APPDATA_PATH}/jellyfin/media
        target: /media
      - type: bind
        source: ${APPDATA_PATH}/jellyfin/media2
        target: /media2
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: ${APPDATA_PATH}/jellyfin/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    labels:
      - com.getarcaneapp.arcane.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - cn1
networks:
  cn1:
    external: true