x-arcane:
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/kometa.png
  urls:
    - https://kometa.wiki/
    - https://mediux.io/

services:
  kometawebui:
    image: registry.kylerockwell.dev/docker/kometawebui:latest
    container_name: kometawebui
    ports:
      - "3333:3000"
    volumes:
      - ${APPDATA_PATH}/kometawebui:/app/data
      - ${APPDATA_PATH}/kometa/configs:/app/data/configs
    environment:
      - DB_PATH=/app/data/kometa.db
    restart: unless-stopped
    networks:
      cn1: null
  kometa:
    image: kometateam/kometa:nightly # Use nightly if you want to be able to set logos
    container_name: kometa
    environment:
      - TZ=America/Chicago
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_TIME=06:00
      - KOMETA_RUN=false
      - KOMETA_NO_MISSING=false
      - KOMETA_NO_REPORT=false
    volumes:
      - ${APPDATA_PATH}/kometa/configs:/config
      - ${APPDATA_PATH}/kometa/logs:/logs
      - ${APPDATA_PATH}/kometa/cache:/cache
    labels:
      - com.getarcaneapp.arcane.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/kometa.png
      - diun.enable=true
    restart: unless-stopped
    networks:
      cn1: null

  imagemaid:
    image: kometateam/imagemaid
    container_name: imagemaid
    environment:
      - TZ=TIMEZONE #optional
    volumes:
      - ${APPDATA_PATH}/config:/config
      - ${APPDATA_PATH}/plex:/plex # Change this to the path of your plex library config
    restart: unless-stopped
    networks:
      cn1: null

networks:
  cn1:
    external: true
