x-arcane:
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/huntarr.png
  urls:
    - https://github.com/plexguide/huntarr

services:
  huntarr:
    image: ghcr.io/plexguide/huntarr:latest
    container_name: huntarr
    labels:
      - com.getarcaneapp.arcane.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/huntarr.png
    networks:
      cn1:
    restart: unless-stopped
    ports:
      - "9705:9705"
    volumes:
      - ${APPDATA_PATH}/huntarr:/config
    environment:
      - TZ=America/Chicago
networks:
  cn1:
    external: true