x-arcane:
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/glances.png
  urls:
    - https://nicolargo.github.io/glances/
    - https://github.com/nicolargo/glances

services:
  glances:
    image: nicolargo/glances:latest-full
    labels:
      - com.getarcaneapp.arcane.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/glances.png
    environment:
      - TZ=${TZ}
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    pid: host
    network_mode: host
    restart: unless-stopped
networks: {}